/* AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
 * Source: .planning/context/brand-copy-v1.json
 * Generated by: scripts/sync-brand-copy.ts
 */

export const brandCopyV1 = {
  "version": "1.0.0",
  "lastUpdated": "2026-02-13",
  "privateInvites": {
    "equinox": {
      "eyebrow": "Private Invitation",
      "title": "Enter The Equinox",
      "subtitle": "A three-day operating reset for leaders ready to move with precision.",
      "dateRange": "March 20-22, 2026",
      "location": "Frequency House, Topanga, California",
      "summary": "A focused in-person immersion designed to clear noise, refine direction, and install stronger execution rhythms.",
      "sections": [
        {
          "title": "What This Is",
          "body": "A private, high-accountability room for founders, operators, and creators who want cleaner decisions and stronger daily command."
        },
        {
          "title": "What You Can Expect",
          "body": "Guided breathwork, focused somatic practices, structured reflection, and integration blocks that convert insight into concrete next actions."
        },
        {
          "title": "Who This Is For",
          "body": "People already carrying responsibility who want sharper mental signal, better emotional regulation, and a more coherent weekly rhythm."
        }
      ],
      "schedule": [
        {
          "day": "Day 1",
          "focus": "Release and Recalibrate",
          "items": [
            "Arrival and field orientation",
            "Guided release and nervous-system downshift",
            "Evening integration circle"
          ]
        },
        {
          "day": "Day 2",
          "focus": "Precision and Power",
          "items": [
            "Morning activation sequence",
            "Focused leadership practices",
            "Execution architecture workshop"
          ]
        },
        {
          "day": "Day 3",
          "focus": "Integration and Direction",
          "items": [
            "Embodiment and cadence alignment",
            "90-day operating commitments",
            "Closing integration and departure"
          ]
        }
      ],
      "pricing": [
        {
          "tier": "Single Day",
          "priceUsd": 333,
          "description": "Access to one full day immersion block."
        },
        {
          "tier": "Two-Day Deepening",
          "priceUsd": 444,
          "description": "Access to two full days plus evening integration."
        },
        {
          "tier": "Full Equinox",
          "priceUsd": 555,
          "description": "Complete three-day immersion experience."
        }
      ],
      "cta": {
        "label": "Request Invitation",
        "supportingText": "Private admission. Limited seats.",
        "defaultHref": "https://www.frequency-house.com/events-24/enter-the-equinox"
      },
      "toneNotes": [
        "cinematic",
        "grounded",
        "direct",
        "no hype"
      ],
      "complianceNotes": [
        "Use structure and function language only.",
        "Do not claim diagnosis, treatment, cure, or prevention of disease.",
        "Keep outcomes framed as support for focus, resilience, and routine."
      ],
      "disclaimer": "This experience is educational and experiential. It is not medical care and is not intended to diagnose, treat, cure, or prevent any disease."
    }
  },
  "platform": {
    "storePage": {
      "metaDescription": "Sound-tuned functional mushroom formulas crafted for focused energy, grounded calm, and daily ritual.",
      "badge": "The Frequency Collection",
      "headlineLine1": "Choose Your",
      "headlineLine2": "Frequency",
      "description": "Dual-extracted functional mushroom formulas crafted in sound fields tuned to 432Hz, 528Hz, and 741Hz.",
      "sections": {
        "capsules": "Resonance Capsules",
        "tinctures": "Dual-Extracted Tinctures",
        "bundles": "Guided Stacks",
        "nutrition": "Functional Nutrition"
      },
      "philosophyTitle": "Everything in nature moves in rhythm.",
      "philosophyQuote": "\"Our formulas are cultivated with care and tuned with intention, so your daily ritual feels clear, grounded, and consistent.\""
    },
    "productCard": {
      "addButton": "Add",
      "detailsLink": "Details",
      "resonanceLabel": "Resonance",
      "subscriptionPrefix": "or",
      "addToastTitleSuffix": "added",
      "addToastDescription": "Added to your collection"
    },
    "productDetail": {
      "backLink": "Back to Collection",
      "frequencyBadgePrefix": "Resonant at",
      "arrivalBadge": "Fresh Batch",
      "ingredientTitle": "Functional Ingredients",
      "primaryCta": "Add to Collection",
      "secondaryCta": "Subscribe & Save 10%",
      "shippingNote": "Free US Shipping over $100",
      "qualityNote": "Lab Tested & Verified",
      "benefits": {
        "extraction": "Dual-Extracted",
        "frequencySuffix": "Sound-Tuned",
        "frequencyFallback": "Ritual-Ready",
        "quality": "Batch Tested"
      }
    },
    "products": {
      "energy": {
        "tagline": "Daily Vitality",
        "description": "Cordyceps-forward capsule blend tuned to 528Hz to support daily drive, creative momentum, and steady stamina."
      },
      "calm": {
        "tagline": "Grounded Clarity",
        "description": "Lion's Mane and Reishi blend tuned to 432Hz to support clear focus, balanced mood, and calm concentration."
      },
      "vibe": {
        "tagline": "Intuitive Flow",
        "description": "Turkey Tail and Maitake blend tuned to 741Hz to support perspective, expression, and reflective practice."
      },
      "cacao-cubes": {
        "tagline": "Functional Chocolate",
        "description": "Handcrafted vegan cacao cubes infused with functional mushroom extracts for a mindful daily ritual."
      },
      "bar-bites": {
        "tagline": "Functional Snacks",
        "description": "Mushroom-infused protein bites formulated for clean energy, steady focus, and on-the-go ritual use."
      },
      "lions-mane-tincture": {
        "tagline": "Dual-Extracted Tincture",
        "description": "Dual-extracted Lion's Mane tincture formulated to support focus, memory, and consistent cognitive performance."
      },
      "reishi-tincture": {
        "tagline": "Dual-Extracted Tincture",
        "description": "Dual-extracted Reishi tincture formulated to support relaxation, recovery, and nightly wind-down."
      },
      "cordyceps-tincture": {
        "tagline": "Dual-Extracted Tincture",
        "description": "Dual-extracted Cordyceps tincture formulated to support daily energy, endurance, and respiratory performance."
      },
      "infini-tea": {
        "tagline": "Functional Tea Blend",
        "description": "Ceremonial mushroom tea blend with adaptogenic herbs for focused mornings and reflective evenings."
      },
      "calm-lions-mane-bundle": {
        "tagline": "Clarity Stack",
        "description": "CALM capsules paired with Lion's Mane tincture for a simple routine centered on focus and grounded calm."
      },
      "energy-cordyceps-bundle": {
        "tagline": "Performance Stack",
        "description": "ENERGY capsules paired with Cordyceps tincture for a focused routine built around stamina and daily output."
      },
      "calm-portal-bundle": {
        "tagline": "Depth Stack",
        "description": "CALM capsules and ritual support products combined into a structured routine for deeper reflective practice."
      }
    },
    "cinematicIntro": {
      "voiceDurationSeconds": 14,
      "subtitles": [
        {
          "start": 0,
          "end": 2.6,
          "text": "EVERYTHING IN NATURE MOVES IN RHYTHM."
        },
        {
          "start": 2.6,
          "end": 5.4,
          "text": "EVERY CELL LISTENS. EVERY SYSTEM RESPONDS."
        },
        {
          "start": 5.4,
          "end": 8.9,
          "text": "WHEN WE STARTED GROWING MUSHROOMS IN SOUND FIELDS, EVERYTHING CHANGED."
        },
        {
          "start": 8.9,
          "end": 12,
          "text": "THE PROCESS BECAME CLEANER, CLEARER, AND MORE INTENTIONAL."
        },
        {
          "start": 12,
          "end": 14,
          "text": "THIS IS FREQUENCY."
        }
      ],
      "enterEyebrow": "Find Your",
      "enterTitle": "FREQUENCY",
      "enterButton": "Enter Experience",
      "enterHint": "Sound on for full experience",
      "findCta": "Explore Your Frequency",
      "scrollHint": "Scroll to explore",
      "collectionLabel": "The Collection",
      "viewCollection": "View Full Collection",
      "footerCredit": "crafted for Frequency"
    },
    "storeChatbot": {
      "mission": "Guide each visitor to the most relevant formula based on their present need and preferred ritual pace.",
      "cadence": "Keep answers concise, warm, and spoken. Use short clauses. Ask one thoughtful follow-up when useful.",
      "products": [
        {
          "name": "ENERGY",
          "frequency": "528Hz",
          "focus": "daily drive, momentum, and output"
        },
        {
          "name": "CALM",
          "frequency": "432Hz",
          "focus": "clear focus, calm concentration, and grounding"
        },
        {
          "name": "VIBE",
          "frequency": "741Hz",
          "focus": "expression, perspective, and reflective flow"
        },
        {
          "name": "Functional Nutrition",
          "frequency": "Ritual",
          "focus": "daily nourishment through cacao, bites, and tea"
        }
      ],
      "rules": [
        "Ask questions that clarify current need before recommending a product.",
        "Use structure/function language only.",
        "Never make medical promises or clinical claims.",
        "Offer one clear next step at the end of each response."
      ],
      "firstMessage": "Welcome. I can help you choose the right formula for today. Are you optimizing for calm, energy, or reflective flow?"
    }
  },
  "storefront": {
    "landing": {
      "badge": "Media · Ritual · Sanctuary",
      "headlineLine1": "Tune Your",
      "headlineLine2": "Resonance",
      "description": "Functional mushroom formulas cultivated in sound fields and crafted for daily consistency.",
      "primaryCta": "Begin Your Ritual",
      "secondaryCta": "Explore The Film",
      "scrollHint": "Descend",
      "philosophyTitleLine1": "Grown in",
      "philosophyTitleLine2": "Rhythm",
      "philosophyBody": "Every formula starts in our controlled cultivation process where mycelium is grown with consistent inputs, careful extraction, and precise handling.",
      "featureCards": [
        {
          "freq": "432 Hz",
          "label": "Supports calm focus and steady presence"
        },
        {
          "freq": "528 Hz",
          "label": "Supports daily drive and constructive momentum"
        },
        {
          "freq": "741 Hz",
          "label": "Supports clarity, reflection, and reset"
        }
      ],
      "quote": "\"Our process follows nature, then refines it with discipline.\"",
      "collectionEyebrow": "The Collection",
      "collectionCta": "Explore The Full Collection"
    },
    "productsIndex": {
      "backLink": "Back to Home",
      "eyebrow": "The Collection",
      "title": "All Formulas",
      "description": "Explore every Frequency formula and choose the format that matches your daily ritual.",
      "viewLabel": "View Formula",
      "footer": "Crafted for daily consistency."
    },
    "productDetail": {
      "backLink": "Back",
      "menu": "Menu",
      "soundInfusedBadge": "Sound-Tuned Formula",
      "collectionEyebrow": "The Resonance Collection",
      "benefitTitle": "Primary Support",
      "frequencyTitle": "Frequency Profile",
      "addCta": "Add to Ritual",
      "shippingNote": "Free carbon-neutral shipping on all orders",
      "ingredientsTitle": "Ingredients",
      "ethicsTitle": "Sourcing",
      "ethicsBody": "Sustainably sourced ingredients and third-party testing for identity and purity.",
      "potencyTitle": "Extraction",
      "potencyBody": "Dual-extracted process designed for consistent bioactive delivery.",
      "suggestedTitle": "Complete the Ritual",
      "viewAll": "View Full Collection"
    },
    "products": {
      "calm": {
        "description": "Focused daily formula tuned to 432 Hz for clear thinking, calm attention, and balanced rhythm.",
        "benefit": "Supports calm focus and daily composure"
      },
      "energy": {
        "description": "Performance-focused daily formula tuned to 741 Hz for clean output, clarity, and consistency.",
        "benefit": "Supports sustained energy and steady focus"
      },
      "vibe": {
        "description": "High-frequency formula tuned to 528 Hz for expressive flow, connection, and creative direction.",
        "benefit": "Supports social flow and creative expression"
      },
      "lions-mane": {
        "description": "Lion's Mane-focused formula for daily cognitive support and clear attention.",
        "benefit": "Supports focus and cognitive performance"
      },
      "cordyceps": {
        "description": "Cordyceps-focused formula for physical output, stamina, and repeatable energy.",
        "benefit": "Supports stamina and endurance"
      },
      "cacao-cubes": {
        "description": "Functional cacao cubes for a measured, mindful ritual format.",
        "benefit": "Supports mindful ritual and steady mood"
      },
      "cacao-bites": {
        "description": "Bite-sized functional cacao for practical daily ritual use.",
        "benefit": "Supports ritual consistency in a compact format"
      },
      "infini-tea": {
        "description": "Functional tea blend for reflective mornings and grounded evenings.",
        "benefit": "Supports calm transition and reflective practice"
      }
    },
    "frequencyDescriptions": {
      "417": "Supports reset and adaptive change",
      "432": "Supports calm focus and grounded rhythm",
      "528": "Supports momentum, connection, and constructive drive",
      "741": "Supports clarity and reflective perspective",
      "Full Spectrum": "Supports broad-spectrum daily balance"
    }
  }
} as const

export type GeneratedBrandCopy = typeof brandCopyV1
